from transformers import AutoTokenizer, AutoModelForCausalLM
import sys
import json

# Load the tokenizer and model from Hugging Face
model_name = "microsoft/Phi-3.5-mini-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

def filter_response(response, src_string, addLength):    
    pos = response.find(src_string)
    if pos != -1:
        if addLength:
            response = response[pos + len(src_string):]
        else:    
            response = response[:pos]

    return response

def generate_response(prompt):
    try:
        # Encode the input text
        inputs = tokenizer(prompt, return_tensors="pt")
        
        # Generate a response with adjusted parameters
        outputs = model.generate(
            **inputs,
            max_length=100,
            do_sample=False,
            num_return_sequences=1,
            pad_token_id=tokenizer.eos_token_id
        )

        # Check if outputs tensor has at least one token
        if outputs.size(0) > 0:
            # Decode and return the response
            response = tokenizer.decode(outputs[0], skip_special_tokens=True)

            response = filter_response(response, "Answer", True)
            response = filter_response(response, "Question", False)                        
            response = response.replace(":", "")
            response = response.replace("\n", "")

            return response
        else:
            return "No response generated by the model."

    except Exception as e:
        return f"An error occurred: {str(e)}"


def main():
    print("Python model ready")  # Signal to C# that Python is ready  (aka PythonScriptService.cs)
    sys.stdout.flush()

    while True:
        # Read input from standard input
        input_line = sys.stdin.readline().strip()
        
        # Exit condition
        if input_line == "exit":
            print("Python exiting")
            sys.stdout.flush()
            break
        
        # Generate response
        prompt = f"Please respond to the following question independently:\n{input_line}"
        response = generate_response(prompt)

        # Debugging information (optional)
        sys.stderr.write(f"DEBUG: Output generated: {response}\n")
        sys.stderr.flush()
        
        print(response)
        sys.stdout.flush()

if __name__ == "__main__":###
    # Check if running in an interactive console
    print("Starting python script...")

    if sys.stdin.isatty():
        # Interactive mode (aka AiModelRunner project)
        print("Running in interactive mode. Type 'exit' to quit.")
        while True:
            input_text = input("You: ")
            if input_text.lower() == "exit":
                print("Exiting interactive mode.")
                break
            
            prompt = f"Please respond to the following question independently:\n{input_text}"
            response = generate_response(prompt)

            print("Model:", response)
    else:
        # Running from the C# command-line app
        print("Running in main mode.")
        main()
